name: Riot
attributes:
  ORGANIZATIONNAME: matrix.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.rst
    - AUTHORS.rst
    - Podfile

configFiles:
  Debug: Config/Common-Debug.xcconfig
  Release: Config/Common-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh

include:
  - path: Targets/Application.yml
  - path: Targets/ApplicationTests.yml
  - path: Targets/ShareExtension.yml
  - path: Targets/SiriIntents.yml
  - path: Targets/NotificationServiceExtension.yml