name: Riot
attributes:
  ORGANIZATIONNAME: matrix.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.rst
    - AUTHORS.rst
    - Podfile

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.0
    SDKROOT: iphoneos
    TARGETED_DEVICE_FAMILY: 1,2
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNREACHABLE_CODE: YES
    DEFINES_MODULE: YES
    ENABLE_STRICT_OBJC_MSGSEND: YES
    GCC_NO_COMMON_BLOCKS: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
  debug:
    COPY_PHASE_STRIP: NO
    ENABLE_TESTABILITY: YES
    GCC_DYNAMIC_NO_PIC: NO
    GCC_OPTIMIZATION_LEVEL: 0
    GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1 $(inherited)
    GCC_SYMBOLS_PRIVATE_EXTERN: NO
    MTL_ENABLE_DEBUG_INFO: YES
    ONLY_ACTIVE_ARCH: YES
  release:
    COPY_PHASE_STRIP: YES
    ENABLE_NS_ASSERTIONS: NO
    MTL_ENABLE_DEBUG_INFO: NO
    SWIFT_COMPILATION_MODE: wholemodule
    VALIDATE_PRODUCT: YES

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh

include:
  - path: Targets/Application.yml
  - path: Targets/ApplicationTests.yml
  - path: Targets/ShareExtension.yml
  - path: Targets/SiriIntents.yml
  - path: Targets/NotificationServiceExtension.yml