name: Riot
attributes:
  ORGANIZATIONNAME: matrix.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.rst
    - AUTHORS.rst
    - Podfile

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh

include:
  - path: Riot/Application.yml
  - path: RiotTests/ApplicationTests.yml
  - path: RiotShareExtension/ShareExtension.yml
  - path: SiriIntents/SiriIntents.yml
  - path: RiotNSE/NotificationServiceExtension.yml