name: Riot
attributes:
  ORGANIZATIONNAME: matrix.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.md
    - AUTHORS.rst
    - Podfile
    - project.yml

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh

packages:
  swift-collections:
    url: https://github.com/apple/swift-collections
    majorVersion: 0.0.5
    
include:
  - path: Riot/target.yml
  - path: RiotTests/target.yml
  - path: RiotShareExtension/target.yml
  - path: SiriIntents/target.yml
  - path: RiotNSE/target.yml
  - path: DesignKit/target.yml
