name: Riot

schemes:
  Riot:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Riot:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
      disableMainThreadChecker: true
    test:
      config: Debug
      disableMainThreadChecker: true
      targets:
      - RiotTests

targets:
  Riot:
    type: application
    platform: iOS

    dependencies:
    - target: RiotShareExtension
    - target: SiriIntents
    - target: RiotNSE

    configFiles:
      Debug: ../Riot/SupportingFiles/App-Debug.xcconfig
      Release: ../Riot/SupportingFiles/App-Release.xcconfig
      
    settings:
      base:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
          CODE_SIGN_STYLE: Automatic
          PROVISIONING_PROFILE_SPECIFIER: 
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE: $(RIOT_PROVISIONING_PROFILE)
          PROVISIONING_PROFILE_SPECIFIER: $(RIOT_PROVISIONING_PROFILE_SPECIFIER)

    preBuildScripts:
    - name: ⚠️ SwiftLint
      runOnlyWhenInstalling: false
      shell: /bin/sh
      script: "${PODS_ROOT}/SwiftLint/swiftlint\n"
    - name: 🛠 SwiftGen
      runOnlyWhenInstalling: false
      shell: /bin/sh
      script: "${PODS_ROOT}/SwiftGen/bin/swiftgen config run --config Tools/SwiftGen/swiftgen-config.yml\n"

    sources:
    - path: ../Tools
      excludes:
        - "Logs"
        - "Release"
        - "Templates/*.sh"
    - path: ../Config
      excludes:
        - "AppConfig.swift"
    - path: ../Riot
      excludes:
        - "Modules/Room/EmojiPicker/Data/EmojiMart/EmojiJSONStore.swift"
        - "Modules/KeyBackup/Recover/Loading"
        - "Modules/KeyBackup/Setup/RecoveryKey"
        - "**/*.strings" # Exclude all strings files

    # Add separately localizable files
    - path: ../Riot/Assets/en.lproj/InfoPlist.strings
    - path: ../Riot/Assets/en.lproj/Localizable.strings
    - path: ../Riot/Assets/en.lproj/Vector.strings
    - path: ../Riot/Assets/fr.lproj/InfoPlist.strings
    - path: ../Riot/Assets/fr.lproj/Localizable.strings
    - path: ../Riot/Assets/fr.lproj/Vector.strings
    - path: ../Riot/Assets/de.lproj/InfoPlist.strings
    - path: ../Riot/Assets/de.lproj/Localizable.strings
    - path: ../Riot/Assets/de.lproj/Vector.strings
    - path: ../Riot/Assets/sq.lproj/InfoPlist.strings
    - path: ../Riot/Assets/sq.lproj/Localizable.strings
    - path: ../Riot/Assets/sq.lproj/Vector.strings
    - path: ../Riot/Assets/vi.lproj/InfoPlist.strings
    - path: ../Riot/Assets/vi.lproj/Localizable.strings
    - path: ../Riot/Assets/vi.lproj/Vector.strings
    - path: ../Riot/Assets/eu.lproj/InfoPlist.strings
    - path: ../Riot/Assets/eu.lproj/Localizable.strings
    - path: ../Riot/Assets/eu.lproj/Vector.strings
    - path: ../Riot/Assets/bg.lproj/InfoPlist.strings
    - path: ../Riot/Assets/bg.lproj/Localizable.strings
    - path: ../Riot/Assets/bg.lproj/Vector.strings
    - path: ../Riot/Assets/nl.lproj/InfoPlist.strings
    - path: ../Riot/Assets/nl.lproj/Localizable.strings
    - path: ../Riot/Assets/nl.lproj/Vector.strings
    - path: ../Riot/Assets/ca.lproj/InfoPlist.strings
    - path: ../Riot/Assets/ca.lproj/Localizable.strings
    - path: ../Riot/Assets/ca.lproj/Vector.strings
    - path: ../Riot/Assets/zh_Hans.lproj/InfoPlist.strings
    - path: ../Riot/Assets/zh_Hans.lproj/Localizable.strings
    - path: ../Riot/Assets/zh_Hans.lproj/Vector.strings
    - path: ../Riot/Assets/ru.lproj/InfoPlist.strings
    - path: ../Riot/Assets/ru.lproj/Localizable.strings
    - path: ../Riot/Assets/ru.lproj/Vector.strings
    - path: ../Riot/Assets/zh_Hant.lproj/InfoPlist.strings
    - path: ../Riot/Assets/zh_Hant.lproj/Localizable.strings
    - path: ../Riot/Assets/zh_Hant.lproj/Vector.strings
    - path: ../Riot/Assets/es.lproj/InfoPlist.strings
    - path: ../Riot/Assets/es.lproj/Localizable.strings
    - path: ../Riot/Assets/es.lproj/Vector.strings
    - path: ../Riot/Assets/ja.lproj/InfoPlist.strings
    - path: ../Riot/Assets/ja.lproj/Localizable.strings
    - path: ../Riot/Assets/ja.lproj/Vector.strings
    - path: ../Riot/Assets/hu.lproj/InfoPlist.strings
    - path: ../Riot/Assets/hu.lproj/Localizable.strings
    - path: ../Riot/Assets/hu.lproj/Vector.strings
    - path: ../Riot/Assets/pl.lproj/InfoPlist.strings
    - path: ../Riot/Assets/pl.lproj/Localizable.strings
    - path: ../Riot/Assets/pl.lproj/Vector.strings
    - path: ../Riot/Assets/cy.lproj/InfoPlist.strings
    - path: ../Riot/Assets/cy.lproj/Localizable.strings
    - path: ../Riot/Assets/cy.lproj/Vector.strings
    - path: ../Riot/Assets/it.lproj/InfoPlist.strings
    - path: ../Riot/Assets/it.lproj/Localizable.strings
    - path: ../Riot/Assets/it.lproj/Vector.strings
    - path: ../Riot/Assets/et.lproj/InfoPlist.strings
    - path: ../Riot/Assets/et.lproj/Localizable.strings
    - path: ../Riot/Assets/et.lproj/Vector.strings
    - path: ../Riot/Assets/is.lproj/Vector.strings