name: Riot
schemes:
  Riot:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Riot:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
      disableMainThreadChecker: true
    test:
      config: Debug
      disableMainThreadChecker: true
      targets:
      - RiotTests
targets:
  Riot:
    dependencies:
    - target: RiotShareExtension
    - target: SiriIntents
    - target: RiotNSE
    platform: iOS
    settings:
      groups:
        - appDefault
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CLANG_ENABLE_MODULES: YES
        CODE_SIGN_ENTITLEMENTS: Riot/SupportingFiles/Riot.entitlements
        ENABLE_BITCODE: NO
        FRAMEWORK_SEARCH_PATHS: $(inherited)
        GCC_PREPROCESSOR_DEFINITIONS: $(inherited)
        HEADER_SEARCH_PATHS: $(inherited)
        INFOPLIST_FILE: Riot/SupportingFiles/Info.plist
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        LIBRARY_SEARCH_PATHS: $(inherited)
        OTHER_CFLAGS: $(inherited)
        OTHER_LDFLAGS: $(inherited)
        OTHER_SWIFT_FLAGS: $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: $(BASE_BUNDLE_IDENTIFIER)
        PRODUCT_NAME: Riot
        SWIFT_OBJC_BRIDGING_HEADER: $(SRCROOT)/$(PRODUCT_NAME)/SupportingFiles/Riot-Bridging-Header.h
        TARGETED_DEVICE_FAMILY: 1,2
        USER_HEADER_SEARCH_PATHS: $(inherited)
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
          CODE_SIGN_STYLE: Automatic
          PROVISIONING_PROFILE_SPECIFIER: 
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE: $(RIOT_PROVISIONING_PROFILE)
          PROVISIONING_PROFILE_SPECIFIER: $(RIOT_PROVISIONING_PROFILE_SPECIFIER)
    sources:
    - path: ../Tools
      excludes:
        - "Logs"
        - "Release"
        - "Templates/*.sh"
    - path: ../Config
      excludes:
        - "AppConfig.swift"
    - path: ../Riot
      excludes:
        - "Modules/Room/EmojiPicker/Data/EmojiMart/EmojiJSONStore.swift"
        - "Modules/KeyBackup/Recover/Loading"
        - "Modules/KeyBackup/Setup/RecoveryKey"
    - path: ../Riot/SupportingFiles/App-Common.xcconfig
      buildPhase: resources
    type: application
    preBuildScripts:
    - name: ⚠️ SwiftLint
      runOnlyWhenInstalling: false
      shell: /bin/sh
      script: "${PODS_ROOT}/SwiftLint/swiftlint\n"
    - name: 🛠 SwiftGen
      runOnlyWhenInstalling: false
      shell: /bin/sh
      script: "${PODS_ROOT}/SwiftGen/bin/swiftgen config run --config Tools/SwiftGen/swiftgen-config.yml\n"